version: '3.8'
services:
    php-apache:
        container_name: vsnippet-open-redirect-invalid-regex-9
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
